server:
  port: 8081
 # context-path: /index
index:
  hello: "Hello,springboot."
spring:
  profiles:
    active: prod
  http:
    encoding:
      charset: utf-8
      force: true
  mvc:
    favicon:
      enabled: false #关闭log
  application:
    name: index-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.0.79:9092,192.168.0.79:9093,192.168.0.79:9094
          zk-nodes: 192.168.0.79:2181
          auto-create-topics: true

      bindings:
        output:
          destination: stream-new
          content-type: text/plain
        input:
          destination: stream-new
#  boot:
#    admin:
#       routes:
#          endpoints:  env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream

#logging:
#  file: /var/log/springboot.log
#  level: debug
eureka:
  client:
    serviceUrl:
          defaultZone: http://10.40.20.147:1234/eureka/
    healthcheck:
          enabled: false #通过 /health 检测client的可用性
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
#security:
#  user:
#    name: admin
#    password: admin
#  basic:
#    enabled: true
info:
    app:
      name: index-service
      version: v1.0.0
endpoints:
  enabled: false
  info:
    enabled: true
#  sensitive: true
#  info:
#    enabled: false
management:
  security:
    enabled: false
  health:
    diskspace:
      enabled: false
###########################


spring.application.name: kafka-streams
spring.cloud.stream.bindings.output:
  destination: counts
spring.cloud.stream.bindings.input:
  destination: words
spring.cloud.stream.kafka.streams.binder:
  brokers: 192.168.0.79:9092
  configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$BytesSerde
    commit.interval.ms: 1000
