server:
  port: 1234

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false  #不向注册中心注册自己
    fetchRegistry: false   #不检测服务
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false #关闭保护机制
  dashboard:
    enabled: false

#management:
#  security:
#    enabled: false
spring:
  cloud:
    dashboard:
      http:
         username: admin
         password: admin

