server:
  port: 8123
eureka:
  instance:
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则），默认30
    lease-renewal-interval-in-seconds: 10
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己），默认90
    lease-expiration-duration-in-seconds: 12
  client:
    registry-fetch-interval-seconds: 10 #eureka client刷新本地缓存时间，默认30
    serviceUrl:
      defaultZone: http://eureka:admin@localhost:9401/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        #netty 路由过滤器，http或https开头
        - id: feign-consumer
          uri: lb://feign-consumer  #LoadBalancerClient负载均衡过滤器（整合eureka注册中心），lb开头
          predicates:
            - Path=/lb/**
          filters:
            #转发请求时去掉1级前缀
            - StripPrefix=1
        - id: spring-cloud-dubbo-provider
          uri: lb://spring-cloud-dubbo-provider
          predicates:
            - Path=/services/**
