server:
  port: 8081
 # context-path: /index
index:
  hello: "Hello,springboot."
spring:
  profiles:
    active: prod
  http:
    encoding:
      charset: utf-8
      force: true
  boot:
    admin:
       routes:
          endpoints:  env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream

  mvc:
    favicon:
      enabled: false #关闭log
  application:
    name: ribbon-consumber
logging:
  file: /var/log/springboot.log
  level: debug
eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:1234/eureka/
management:
  security:
    enabled: false